version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: reggit
    volumes:
      - reggit-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  reggit-data: {}
